"""empty message

Revision ID: ebab1388de9d
Revises: 11bd9e5e267e
Create Date: 2019-06-13 18:05:04.408172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebab1388de9d'
down_revision = '11bd9e5e267e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_register', sa.Column('modified_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'map_register', 'users', ['modified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'map_register', type_='foreignkey')
    op.drop_column('map_register', 'modified_by')
    # ### end Alembic commands ###
